export const CONNECT_WALLER = "CONNECT_WALLET";
export const SWAP_TOKEN = "SWAP_TOKEN";
export const SET_SIGNER = "SET_SIGNER";
export const SET_PROVIDER = "SET_PROVIDER";
export const SET_SIGNER_ADDRESS = "SET_SIGNER_ADDRESS";
